/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CloudinaryResponse
 */
export interface CloudinaryResponse {
    /**
     * 
     * @type {string}
     * @memberof CloudinaryResponse
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CloudinaryResponse
     */
    'url'?: string;
}

