/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WeeklyReportResponse } from './weekly-report-response';

/**
 * 
 * @export
 * @interface CustomApiResponseWeeklyReportResponse
 */
export interface CustomApiResponseWeeklyReportResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseWeeklyReportResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseWeeklyReportResponse
     */
    'message'?: string;
    /**
     * 
     * @type {WeeklyReportResponse}
     * @memberof CustomApiResponseWeeklyReportResponse
     */
    'result'?: WeeklyReportResponse;
}

