/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LabMemberResponse } from './lab-member-response';

/**
 * 
 * @export
 * @interface CustomApiResponseLabMemberResponse
 */
export interface CustomApiResponseLabMemberResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseLabMemberResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLabMemberResponse
     */
    'message'?: string;
    /**
     * 
     * @type {LabMemberResponse}
     * @memberof CustomApiResponseLabMemberResponse
     */
    'result'?: LabMemberResponse;
}

