/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LabEventRespond } from './lab-event-respond';

/**
 * 
 * @export
 * @interface CustomApiResponseLabEventRespond
 */
export interface CustomApiResponseLabEventRespond {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseLabEventRespond
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLabEventRespond
     */
    'message'?: string;
    /**
     * 
     * @type {LabEventRespond}
     * @memberof CustomApiResponseLabEventRespond
     */
    'result'?: LabEventRespond;
}

