/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EventLogRespond } from './event-log-respond';

/**
 * 
 * @export
 * @interface CustomApiResponseEventLogRespond
 */
export interface CustomApiResponseEventLogRespond {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseEventLogRespond
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseEventLogRespond
     */
    'message'?: string;
    /**
     * 
     * @type {EventLogRespond}
     * @memberof CustomApiResponseEventLogRespond
     */
    'result'?: EventLogRespond;
}

