/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CheckPasswordResponse } from './check-password-response';

/**
 * 
 * @export
 * @interface CustomApiResponseCheckPasswordResponse
 */
export interface CustomApiResponseCheckPasswordResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseCheckPasswordResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseCheckPasswordResponse
     */
    'message'?: string;
    /**
     * 
     * @type {CheckPasswordResponse}
     * @memberof CustomApiResponseCheckPasswordResponse
     */
    'result'?: CheckPasswordResponse;
}

