/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LabResponse } from './lab-response';

/**
 * 
 * @export
 * @interface CustomApiResponseLabResponse
 */
export interface CustomApiResponseLabResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseLabResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLabResponse
     */
    'message'?: string;
    /**
     * 
     * @type {LabResponse}
     * @memberof CustomApiResponseLabResponse
     */
    'result'?: LabResponse;
}

