/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomApiResponseObject
 */
export interface CustomApiResponseObject {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseObject
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseObject
     */
    'message'?: string;
    /**
     * 
     * @type {object}
     * @memberof CustomApiResponseObject
     */
    'result'?: object;
}

