/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LogDetailRespond } from './log-detail-respond';

/**
 * 
 * @export
 * @interface CustomApiResponseLogDetailRespond
 */
export interface CustomApiResponseLogDetailRespond {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseLogDetailRespond
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLogDetailRespond
     */
    'message'?: string;
    /**
     * 
     * @type {LogDetailRespond}
     * @memberof CustomApiResponseLogDetailRespond
     */
    'result'?: LogDetailRespond;
}

