/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NotificationResponse } from './notification-response';

/**
 * 
 * @export
 * @interface CustomApiResponseListNotificationResponse
 */
export interface CustomApiResponseListNotificationResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListNotificationResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListNotificationResponse
     */
    'message'?: string;
    /**
     * 
     * @type {Array<NotificationResponse>}
     * @memberof CustomApiResponseListNotificationResponse
     */
    'result'?: Array<NotificationResponse>;
}

