/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ErrorApiResponse
 */
export interface ErrorApiResponse {
    /**
     * Response code
     * @type {number}
     * @memberof ErrorApiResponse
     */
    'code'?: number;
    /**
     * Error message
     * @type {string}
     * @memberof ErrorApiResponse
     */
    'message'?: string;
}

