/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EventGuestCreationRequest } from './event-guest-creation-request';
// May contain unused imports in some cases
// @ts-ignore
import type { LabEventCreationRequest } from './lab-event-creation-request';

/**
 * 
 * @export
 * @interface EventWIthGuestCreationRequest
 */
export interface EventWIthGuestCreationRequest {
    /**
     * 
     * @type {LabEventCreationRequest}
     * @memberof EventWIthGuestCreationRequest
     */
    'eventInfo'?: LabEventCreationRequest;
    /**
     * 
     * @type {Array<EventGuestCreationRequest>}
     * @memberof EventWIthGuestCreationRequest
     */
    'guestList'?: Array<EventGuestCreationRequest>;
}

