/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventLogCreationRequest
 */
export interface EventLogCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof EventLogCreationRequest
     */
    'eventId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventLogCreationRequest
     */
    'guestId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventLogCreationRequest
     */
    'recordType'?: EventLogCreationRequestRecordTypeEnum;
}

export const EventLogCreationRequestRecordTypeEnum = {
    CHECKIN: 'CHECKIN',
    CHECKOUT: 'CHECKOUT'
} as const;

export type EventLogCreationRequestRecordTypeEnum = typeof EventLogCreationRequestRecordTypeEnum[keyof typeof EventLogCreationRequestRecordTypeEnum];


