/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EventLogRespond
 */
export interface EventLogRespond {
    /**
     * 
     * @type {string}
     * @memberof EventLogRespond
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventLogRespond
     */
    'guestId'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventLogRespond
     */
    'guestName'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventLogRespond
     */
    'recordType'?: EventLogRespondRecordTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EventLogRespond
     */
    'recordTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof EventLogRespond
     */
    'status'?: EventLogRespondStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof EventLogRespond
     */
    'photoURL'?: string;
}

export const EventLogRespondRecordTypeEnum = {
    CHECKIN: 'CHECKIN',
    CHECKOUT: 'CHECKOUT'
} as const;

export type EventLogRespondRecordTypeEnum = typeof EventLogRespondRecordTypeEnum[keyof typeof EventLogRespondRecordTypeEnum];
export const EventLogRespondStatusEnum = {
    SUCCESS: 'SUCCESS',
    ILLEGAL: 'ILLEGAL',
    AUTO: 'AUTO'
} as const;

export type EventLogRespondStatusEnum = typeof EventLogRespondStatusEnum[keyof typeof EventLogRespondStatusEnum];


