/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IntrospectResponse
 */
export interface IntrospectResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IntrospectResponse
     */
    'valid'?: boolean;
}

