/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InviteManagerForLabRequest
 */
export interface InviteManagerForLabRequest {
    /**
     * 
     * @type {string}
     * @memberof InviteManagerForLabRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof InviteManagerForLabRequest
     */
    'labId': string;
}

