/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Lab } from './lab';
// May contain unused imports in some cases
// @ts-ignore
import type { MyUserResponse } from './my-user-response';
// May contain unused imports in some cases
// @ts-ignore
import type { Role } from './role';

/**
 * 
 * @export
 * @interface LabMemberResponse
 */
export interface LabMemberResponse {
    /**
     * 
     * @type {MyUserResponse}
     * @memberof LabMemberResponse
     */
    'myUserResponse'?: MyUserResponse;
    /**
     * 
     * @type {Role}
     * @memberof LabMemberResponse
     */
    'role'?: Role;
    /**
     * 
     * @type {string}
     * @memberof LabMemberResponse
     */
    'memberStatus'?: LabMemberResponseMemberStatusEnum;
    /**
     * 
     * @type {Lab}
     * @memberof LabMemberResponse
     */
    'lab'?: Lab;
}

export const LabMemberResponseMemberStatusEnum = {
    ACTIVE: 'ACTIVE',
    BLOCKED: 'BLOCKED'
} as const;

export type LabMemberResponseMemberStatusEnum = typeof LabMemberResponseMemberStatusEnum[keyof typeof LabMemberResponseMemberStatusEnum];


