/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LabMemberCreationRequest
 */
export interface LabMemberCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'labId': string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'dob'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberCreationRequest
     */
    'role': string;
}

