/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MyUserResponse } from './my-user-response';

/**
 * 
 * @export
 * @interface LabMemberInfoRespond
 */
export interface LabMemberInfoRespond {
    /**
     * 
     * @type {MyUserResponse}
     * @memberof LabMemberInfoRespond
     */
    'myUserResponse'?: MyUserResponse;
    /**
     * 
     * @type {string}
     * @memberof LabMemberInfoRespond
     */
    'status'?: LabMemberInfoRespondStatusEnum;
}

export const LabMemberInfoRespondStatusEnum = {
    ACTIVE: 'ACTIVE',
    BLOCKED: 'BLOCKED'
} as const;

export type LabMemberInfoRespondStatusEnum = typeof LabMemberInfoRespondStatusEnum[keyof typeof LabMemberInfoRespondStatusEnum];


