/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LabMemberKey } from './lab-member-key';

/**
 * 
 * @export
 * @interface LabMemberUpdateRequest
 */
export interface LabMemberUpdateRequest {
    /**
     * 
     * @type {LabMemberKey}
     * @memberof LabMemberUpdateRequest
     */
    'labMemberKey'?: LabMemberKey;
    /**
     * 
     * @type {string}
     * @memberof LabMemberUpdateRequest
     */
    'memberStatus'?: LabMemberUpdateRequestMemberStatusEnum;
}

export const LabMemberUpdateRequestMemberStatusEnum = {
    ACTIVE: 'ACTIVE',
    BLOCKED: 'BLOCKED'
} as const;

export type LabMemberUpdateRequestMemberStatusEnum = typeof LabMemberUpdateRequestMemberStatusEnum[keyof typeof LabMemberUpdateRequestMemberStatusEnum];


