/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LabEventUpdateRequest
 */
export interface LabEventUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof LabEventUpdateRequest
     */
    'eventId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventUpdateRequest
     */
    'labId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventUpdateRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventUpdateRequest
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventUpdateRequest
     */
    'endTime'?: string;
}

