/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LabMemberResponse
 */
export interface LabMemberResponse {
    /**
     * 
     * @type {string}
     * @memberof LabMemberResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberResponse
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberResponse
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberResponse
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabMemberResponse
     */
    'status'?: LabMemberResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LabMemberResponse
     */
    'lastRecord'?: string;
}

export const LabMemberResponseStatusEnum = {
    ACTIVE: 'ACTIVE',
    BLOCKED: 'BLOCKED'
} as const;

export type LabMemberResponseStatusEnum = typeof LabMemberResponseStatusEnum[keyof typeof LabMemberResponseStatusEnum];


