/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LabUpdateRequest
 */
export interface LabUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof LabUpdateRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof LabUpdateRequest
     */
    'location'?: string;
}

