/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LabEventRespond
 */
export interface LabEventRespond {
    /**
     * 
     * @type {string}
     * @memberof LabEventRespond
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventRespond
     */
    'labId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventRespond
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventRespond
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof LabEventRespond
     */
    'endTime'?: string;
}

