/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LogCreationRequest
 */
export interface LogCreationRequest {
    /**
     * 
     * @type {string}
     * @memberof LogCreationRequest
     */
    'labId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogCreationRequest
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogCreationRequest
     */
    'recordType'?: LogCreationRequestRecordTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LogCreationRequest
     */
    'photoURL'?: string;
}

export const LogCreationRequestRecordTypeEnum = {
    CHECKIN: 'CHECKIN',
    CHECKOUT: 'CHECKOUT'
} as const;

export type LogCreationRequestRecordTypeEnum = typeof LogCreationRequestRecordTypeEnum[keyof typeof LogCreationRequestRecordTypeEnum];


