/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LogDetailRespond
 */
export interface LogDetailRespond {
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'userFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'userLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'recordType'?: LogDetailRespondRecordTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'recordTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'status'?: LogDetailRespondStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'logType'?: LogDetailRespondLogTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LogDetailRespond
     */
    'photoURL'?: string;
}

export const LogDetailRespondRecordTypeEnum = {
    CHECKIN: 'CHECKIN',
    CHECKOUT: 'CHECKOUT'
} as const;

export type LogDetailRespondRecordTypeEnum = typeof LogDetailRespondRecordTypeEnum[keyof typeof LogDetailRespondRecordTypeEnum];
export const LogDetailRespondStatusEnum = {
    SUCCESS: 'SUCCESS',
    ILLEGAL: 'ILLEGAL',
    AUTO: 'AUTO'
} as const;

export type LogDetailRespondStatusEnum = typeof LogDetailRespondStatusEnum[keyof typeof LogDetailRespondStatusEnum];
export const LogDetailRespondLogTypeEnum = {
    LEGAL: 'LEGAL',
    ILLEGAL: 'ILLEGAL',
    AUTO: 'AUTO'
} as const;

export type LogDetailRespondLogTypeEnum = typeof LogDetailRespondLogTypeEnum[keyof typeof LogDetailRespondLogTypeEnum];


