/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LogRespond
 */
export interface LogRespond {
    /**
     * 
     * @type {string}
     * @memberof LogRespond
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogRespond
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogRespond
     */
    'userFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogRespond
     */
    'userLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogRespond
     */
    'recordType'?: LogRespondRecordTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LogRespond
     */
    'recordTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof LogRespond
     */
    'status'?: LogRespondStatusEnum;
}

export const LogRespondRecordTypeEnum = {
    CHECKIN: 'CHECKIN',
    CHECKOUT: 'CHECKOUT'
} as const;

export type LogRespondRecordTypeEnum = typeof LogRespondRecordTypeEnum[keyof typeof LogRespondRecordTypeEnum];
export const LogRespondStatusEnum = {
    SUCCESS: 'SUCCESS',
    BLOCKED: 'BLOCKED'
} as const;

export type LogRespondStatusEnum = typeof LogRespondStatusEnum[keyof typeof LogRespondStatusEnum];


