/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RoleResponse } from './role-response';

/**
 * 
 * @export
 * @interface MyUserResponse
 */
export interface MyUserResponse {
    /**
     * 
     * @type {string}
     * @memberof MyUserResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyUserResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyUserResponse
     */
    'firstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyUserResponse
     */
    'lastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyUserResponse
     */
    'dob'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyUserResponse
     */
    'gender'?: string;
    /**
     * 
     * @type {string}
     * @memberof MyUserResponse
     */
    'photoURL'?: string;
    /**
     * 
     * @type {Set<RoleResponse>}
     * @memberof MyUserResponse
     */
    'roles'?: Set<RoleResponse>;
}

