/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationResponse
 */
export interface NotificationResponse {
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'type'?: NotificationResponseTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof NotificationResponse
     */
    'createdAt'?: string;
}

export const NotificationResponseTypeEnum = {
    YES_NO: 'YES_NO',
    TEXT: 'TEXT'
} as const;

export type NotificationResponseTypeEnum = typeof NotificationResponseTypeEnum[keyof typeof NotificationResponseTypeEnum];


