/* tslint:disable */
/* eslint-disable */
/**
 * My REST API
 * Some custom description of API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DailyReportResponse } from './daily-report-response';

/**
 * 
 * @export
 * @interface WeeklyReportResponse
 */
export interface WeeklyReportResponse {
    /**
     * 
     * @type {number}
     * @memberof WeeklyReportResponse
     */
    'totalUsers'?: number;
    /**
     * 
     * @type {number}
     * @memberof WeeklyReportResponse
     */
    'weeklyAccess'?: number;
    /**
     * 
     * @type {Array<DailyReportResponse>}
     * @memberof WeeklyReportResponse
     */
    'weeklyLogReport'?: Array<DailyReportResponse>;
}

