generatorName: typescript-axios
inputSpec: "https://unilabpass-backend.onrender.com/identity/v3/api-docs"
outputDir: "api"
apiPackage: api
modelPackage: models
additionalProperties:
  withSeparateModelsAndApi: true
  useSingleRequestParameter: true
  supportsES6: true
  modelPropertyNaming: camelCase
  enumPropertyNaming: original
  typescriptThreePlus: true
  useTags: true
  npmName: "@api"
  npmVersion: "1.0.0"
